name: Publish Docker

on:
  workflow_dispatch:

jobs:
  publish:
    uses: Dofus-Batteries-Included/workflows/.github/workflows/docker_build_publish.yml@main
    with:
      docker_image_name: ddc_api
      docker_file: DDC.Api/Dockerfile
  
  deploy:
    needs: publish
    if: ${{ needs.publish.outputs.latest_has_changed == 'true' }}
    uses: Dofus-Batteries-Included/workflows/.github/workflows/docker_deploy.yml@main
    with:
      directory: /home/debian/ddc
    secrets: 
      ssh_host: ${{ secrets.SSH_HOST }}
      ssh_user: ${{ secrets.SSH_USER }}
      ssh_key: ${{ secrets.SSH_KEY }}

permissions:
  packages: write